[pytest]
addopts = --html=reports/reporte_final.html --self-contained-html -v
markers =
    ui: Pruebas de Interfaz de Usuario con Selenium WebDriver.
    api: Pruebas de Backend con la librería Requests.
html_report_title = Reporte Final de Pruebas Automatizadas - UTN